- name: "create directory  {{ basedir }}"
  file: path={{ basedir }} state=directory owner={{ project_user }}
  only_if: '"{{ envname }}" != "vagrant"'

- name: install packages for node-canvas
  apt: pkg={{ item }} state=present
  with_items:
    - libcairo2-dev
    - libjpeg8-dev
    - libpango1.0-dev
    - libgif-dev

- name: clone 'muchmala-cmn' to '$dir'
  sudo: false
  git:
    repo=$repo
    dest=$dir
    version=$branch
  only_if: '"$envname" != "vagrant"'

- name: npm install
  sudo: false
  npm: path={{ dir }}

- name: create /usr/lib/node_modules
  file:
    path="/usr/lib/node_modules"
    state=directory
    owner=root
    group=root
    mode=775

- name: link muchmala-cmn into /usr/lib/node_modules/muchmala-cmn
  file:
    src="{{ dir }}"
    dest="/usr/lib/node_modules/muchmala-cmn"
    state=link
    owner=root
    group=root
