- name: add nginx PPA
  apt_repository: repo=ppa:nginx/stable
  register: result

- name: apt-get update
  apt: update_cache=yes
  when_changed: $result

- name: install 'nginx'
  apt: pkg=nginx
  register: result

- name: disable 'nginx'
  service: name=nginx enabled=no state=stopped
  when_changed: $result
