- hosts: io
  connection: ssh
  gather_facts: false
  sudo: true

  vars_files:
    - "vars/common.yml"
    - [ "secrets/${envname}.yml", "environments/${envname}.yml" ]

  roles:
    - enver
    - nodejs

    - role: muchmala-cmn
      repo: ${muchmala_cmn.repo}
      dir: ${muchmala_cmn.dir}
      branch: ${muchmala_cmn.branch}

    - role: muchmala-service-template
      name: muchmala-io
      repo: ${muchmala_io.repo}
      dir: ${muchmala_io.dir}
      branch: ${muchmala_io.branch}
      autostart: ${muchmala_io.autostart}
      env: ${muchmala_io.env}
